HOST lewis.lbl.gov
only_i 14
only_code None
force_amber_prep True
dry_run False
1 1z3z,A,2.900,1zod,A,1.800
2 1psi,A,2.920,3ndd,A,1.500
3 3bpo,A,3.000,3l5w,I,2.000
4 1e6j,P,3.000,3mge,A,1.900
5 1r46,A,3.250,3hg3,A,1.900
6 2j0g,A,2.850,2j1g,A,1.950
7 1nsk,L,2.800,3bbb,A,1.300
... 14 3bbb
/net/chevy/raid1/nigel/amber/hi_lo
/net/chevy/raid1/nigel/amber/hi_lo/bb/3bbb
3bbb.pdb 4phenix_3bbb.pdb
local_archive None
archive PDB None
Reading from local mirror:
  /net/cci/pdb_mirror/pdb/bb/pdb3bbb.ent.gz
Model saved to /net/lewis/raid1/scratch1/nigel/amber/hi_lo/bb/3bbb/3bbb.pdb
Traceback (most recent call last):
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 199, in <module>
    run2(sys.argv[1:])
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 155, in run2
    files.append(get_pdb(id, data_type_, mirror, log, format=data_format))
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 213, in get_pdb
    data = fetch(id, data_type, mirror=mirror, format=format, log=log)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 150, in fetch
    data = libtbx.utils.urlopen(url)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/libtbx/utils.py", line 2069, in urlopen
    return urllib2.urlopen(*args, **kwds)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>
local_archive None
archive PDB None
Reading from local mirror:
  /net/cci/pdb_mirror/pdb/bb/pdb3bbb.ent.gz
Model saved to /net/lewis/raid1/scratch1/nigel/amber/hi_lo/bb/3bbb/3bbb.pdb
Traceback (most recent call last):
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 199, in <module>
    run2(sys.argv[1:])
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 155, in run2
    files.append(get_pdb(id, data_type_, mirror, log, format=data_format))
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 213, in get_pdb
    data = fetch(id, data_type, mirror=mirror, format=format, log=log)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 150, in fetch
    data = libtbx.utils.urlopen(url)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/libtbx/utils.py", line 2069, in urlopen
    return urllib2.urlopen(*args, **kwds)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>

==================================================
Summary of pdb4amber for: 3bbb.pdb
===================================================
REDUCE returned non-zero exit status: See reduce_info.log for more details

----------Chains
The following (original) chains have been found:
A
B
C
D
E
F

---------- Alternate Locations (Original Residues!))

The following residues had alternate locations:
ASN_81
SER_143
GLU_173
ARG_192
GLU_229
MET_240
SER_275
ALA_276
SER_294
ARG_340
ALA_341
ASN_380
VAL_381
SER_442
SER_593
TYR_664
MET_665
ASN_679
SER_741
TYR_815
MET_816
LEU_829
MET_838
SER_892
HOH_1059

---------- Mising heavy atom(s)

None
The alternate coordinates have been discarded.
Only the first occurrence for each atom was kept.
not prmtop_filename /net/lewis/scratch1/nigel/amber/hi_lo/bb/3bbb/4amber_3bbb.prmtop
not prmtop_filename /net/chevy/raid1/nigel/amber/hi_lo/bb/3bbb/4amber_3bbb.prmtop

	Running AmberPrep : 3bbb.pdb


==================================================
Running pdb4amber on 3bbb.pdb
==================================================

==================================================
Setting up library files for non-standard residues
==================================================

==================================================
Running elbow/antechamber for DG 
==================================================
Traceback (most recent call last):
  File "run_tests_local.py", line 321, in <module>
    run(*tuple(args))
  File "run_tests_local.py", line 305, in run
    w2 = run_all_tests(code, force_amber_prep=force_amber_prep)
  File "run_tests_local.py", line 93, in run_all_tests
    "clean=on",
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/amber_adaptbx/command_line/AmberPrepClass.py", line 961, in run
    prefer_input_method=inputs.antechamber.prefer_input_method,
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/amber_adaptbx/command_line/AmberPrepClass.py", line 393, in process_ligands
    _run_elbow_antechamber(self.pdb_hierarchy, residue_name, debug=debug)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/amber_adaptbx/command_line/AmberPrepClass.py", line 877, in _run_elbow_antechamber
    pdb_mol.Bondise(add_bond_order=False)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/elbow/elbow/chemistry/BondTopologyMixins.py", line 161, in Bondise
    self.CheckBondise(keep_all_atoms=keep_all_atoms)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/elbow/elbow/chemistry/BondTopologyMixins.py", line 871, in CheckBondise
    bonded = self._get_bonded_to_atom()
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/elbow/elbow/chemistry/BondTopologyMixins.py", line 786, in _get_bonded_to_atom
    bonded = [self[i].index]
IndexError: list index out of range
