HOST lewis.lbl.gov
only_i 133
only_code None
force_amber_prep True
dry_run False
... 133 1fss
/net/chevy/raid1/nigel/amber/hi_lo
/net/chevy/raid1/nigel/amber/hi_lo/fs/1fss
1fss.pdb 4phenix_1fss.pdb
local_archive None
archive PDB None
Reading from local mirror:
  /net/cci/pdb_mirror/pdb/fs/pdb1fss.ent.gz
Model saved to /net/lewis/raid1/scratch1/nigel/amber/hi_lo/fs/1fss/1fss.pdb
Traceback (most recent call last):
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 199, in <module>
    run2(sys.argv[1:])
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 155, in run2
    files.append(get_pdb(id, data_type_, mirror, log, format=data_format))
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 213, in get_pdb
    data = fetch(id, data_type, mirror=mirror, format=format, log=log)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 150, in fetch
    data = libtbx.utils.urlopen(url)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/libtbx/utils.py", line 2069, in urlopen
    return urllib2.urlopen(*args, **kwds)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>
local_archive None
archive PDB None
Reading from local mirror:
  /net/cci/pdb_mirror/pdb/fs/pdb1fss.ent.gz
Model saved to /net/lewis/raid1/scratch1/nigel/amber/hi_lo/fs/1fss/1fss.pdb
Traceback (most recent call last):
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 199, in <module>
    run2(sys.argv[1:])
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 155, in run2
    files.append(get_pdb(id, data_type_, mirror, log, format=data_format))
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 213, in get_pdb
    data = fetch(id, data_type, mirror=mirror, format=format, log=log)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 150, in fetch
    data = libtbx.utils.urlopen(url)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/libtbx/utils.py", line 2069, in urlopen
    return urllib2.urlopen(*args, **kwds)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>

==================================================
Summary of pdb4amber for: 1fss.pdb
===================================================

----------Chains
The following (original) chains have been found:
A
B

---------- Alternate Locations (Original Residues!))

The following residues had alternate locations:
None

---------- Mising heavy atom(s)

HIS_483 misses 5 heavy atom(s)
SER_484 misses 1 heavy atom(s)
GLN_485 misses 4 heavy atom(s)
GLU_486 misses 4 heavy atom(s)
SER_487 misses 1 heavy atom(s)
LYS_488 misses 4 heavy atom(s)
not prmtop_filename /net/lewis/scratch1/nigel/amber/hi_lo/fs/1fss/4amber_1fss.prmtop
not prmtop_filename /net/chevy/raid1/nigel/amber/hi_lo/fs/1fss/4amber_1fss.prmtop

	Running AmberPrep : 1fss.pdb


==================================================
Running pdb4amber on 1fss.pdb
==================================================

==================================================
Setting up library files for non-standard residues
==================================================

==================================================
Running elbow/antechamber for NAG 
==================================================

==================================================
Summary of pdb4amber for: 1fss_4tleap_uc1.pdb
===================================================

----------Chains
The following (original) chains have been found:
A
B

---------- Alternate Locations (Original Residues!))

The following residues had alternate locations:
None

---------- Mising heavy atom(s)

None

MoleculeClass :  C: 8  N: 1  O: 6 (CHEMICAL COMPONENTS format)
	30 atoms
	30 bonds
	53 angles
	79 dihedrals
	1 rings (groups, rings, atoms) 1 6
	5 chirals : R R R S R 

~> antechamber -i 4antechamber_NAG.pdb -fi pdb -o NAG.mol2 -fo mol2       -nc 0 -m 1 -s 2 -pf y -c bcc -at gaff2 -ek "qm_theory='AM1',grms_tol=0.0005,scfconv=1.d-10,maxcyc=0,ndiis_attempts=700,"


~> parmchk2 -s 2 -i NAG.mol2 -f mol2 -o NAG.frcmod


==================================================
Preparing asu files and 4phenix_1fss.pdb
==================================================

~> tleap -f 1fss_asu_tleap_input_run

Checking output filenames
  file : 1fss_asu.prmtop
  file : 1fss_asu.rst7

~> ChBox -c 1fss_asu.rst7 -o 1fss_asu.rst7 -X 87.39 -Y 115.0 -Z 67.47 -al 90.0 -bt 90.0 -gm 90.0 


============================================================
Preparing unit cell files: 4amber_1fss.prmtop and 4amber_1fss.rst7
============================================================

~> UnitCell -p 1fss_4UnitCell.pdb -o 1fss_4tleap_uc1.pdb


~> tleap -f 1fss_uc_tleap_input_run

Checking output filenames
  file : 1fss_uc.prmtop
  file : 1fss_uc.rst7

~> ChBox -c 1fss_uc.rst7 -o 1fss_uc.rst7 -X 87.39 -Y 115.0 -Z 67.47 -al 90.0 -bt 90.0 -gm 90.0 


==================================================
Minimizing input coordinates.
==================================================

~> sander -O -i 1fss_amber_all.in -p 4amber_1fss.prmtop -c 4amber_1fss.rst7 -o 1fss.min.out            -ref 4amber_1fss.rst7 -r 4amber_1fss.min.rst7

Traceback (most recent call last):
  File "run_tests_local.py", line 323, in <module>
    run(*tuple(args))
  File "run_tests_local.py", line 307, in run
    w2 = run_all_tests(code, force_amber_prep=force_amber_prep)
  File "run_tests_local.py", line 93, in run_all_tests
    "clean=on",
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/amber_adaptbx/command_line/AmberPrepClass.py", line 1034, in run
    minimization_options=actions.minimization_options)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/amber_adaptbx/command_line/AmberPrepClass.py", line 685, in run_minimise
    assert (ero.return_code == 0)
AssertionError
